name: ggate # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '4.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A logic gate circuit simulator # 79 char long summary
description: |
  A logic gate simulator for linux developed with Gtk and python.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

architectures:
  - build-on: amd64

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  ggate:
    command: ggate
    plugs: [home]

parts:
  ggate:
    plugin: python
    source: https://github.com/astraldev/GGate.git
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      
