name: ggate
base: core22
version: '5.0.0'
summary: A digital logic circuit simulator and designer
description: |
  GGate is a digital logic circuit simulator that allows you to design
  and test digital circuits using standard logic gates and components.
  Features include:
  * Interactive circuit design
  * Real-time simulation
  * Timing diagram analysis
  * Support for basic and complex logic gates
  * Save and load circuit designs
grade: stable
confinement: strict

architectures:
  - build-on: amd64

plugs:
  gtk-4-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-4-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  desktop:
    interface: desktop
  wayland:
    interface: wayland
  x11:
    interface: x11

apps:
  ggate:
    command: bin/ggate
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - wayland
      - x11
      - gtk-4-themes
      - icon-themes

parts:
  poetry-deps:
    plugin: nil
    source: .
    override-build: |
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="/root/.local/bin:$PATH"
      poetry config virtualenvs.create false
      poetry install --no-dev --no-interaction
    build-packages:
      - python3
      - curl

  ggate:
    after: [poetry-deps]
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/snap/ggate/current/usr
    build-packages:
      - pkg-config
      - python3-dev
      - python3-gi-dev
      - libcairo2-dev
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - python3-gi
      - python3-gi-cairo
