name: Snap Build

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: build-aux/snapcraft

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v7
        with:
          name: ggate-snap
          path: ${{ steps.snapcraft.outputs.snap }}
